### ISSUE TITLE
1차 완성 Frontend 버그 수정 및 편의성 개선

### ISSUE THREAD

**Issue by MoohyunSong** [ddps-lab/Callisto#16]
Frontend 관련하여 아래 내용에 대해 확인하고 수정작업을 진행합니다.
- [x] 간헐적으로 API가 여러번 호출되는 현상
- [x] 간헐적으로 API 호출이 실패하는 현상
- [x] Jupyter Endpoint URL 복사 또는 클릭시 새탭오픈이 되지 않는 문제 (#20)
- [x] 현재 2개 이상의 Jupyter Instance를 생성할 수 없는 문제 (#21)
- [x] 현재 로그아웃 버튼이 없어 추가해야할 것으로 보임. (#22)
- [x] 현재 RefreshToken을 활용해 Token을 자동으로 Update하지 않아 1시간뒤면 무조건 권한이 상실되는 문제 개선이 필요함. (#22)
- [x] 현재 Token이 만료되거나 API 호출이 실패하여도 delete 동작에 한해서는 Frontend에서 성공했다는 결과만 나타남. (#22)
- [x] Jupyter page에서 새로고침을 하였을 때, 목록 업데이트가 되지 않는 문제 해결 필요 (#22)
- [x] Jupyter Console에서 Table의 순서를 변경했으면 좋겠습니다. (#22)
- [x] 회원가입 시, Last Name (Family Name), First Name 순으로 입력하는데 이게 반대로 되면 더 자연스러울 것 같습니다. (#22)
